import { buildCaptionFrames } from './dist/src/captions/svg.js';
import { groupIntoCues } from './dist/src/captions/group.js';
import { resolveStyle } from './dist/src/captions/style.js';
import { initShaper } from './dist/src/text/shaper.js';
await initShaper();
// simulate a 30-minute podcast at ~2.5 words/sec
const N = 4500;
const words = Array.from({length:N},(_,i)=>({text:`शब्द${i%50}`,start:i*0.4,end:i*0.4+0.35,confidence:1,type:'word',keep:true}));
const t={words,language:'hi',duration:N*0.4+1,provider:'fixture',hasWordTimings:true};
const cues=groupIntoCues(t);
const style=resolveStyle('bold',1920);
const before=process.memoryUsage().heapUsed;
const t0=Date.now();
const frames=await buildCaptionFrames(cues,{width:1080,height:1920,style,highlight:'active-word'});
const after=process.memoryUsage().heapUsed;
const svgBytes=frames.reduce((n,f)=>n+f.svg.length,0);
console.log(`words: ${N}  cues: ${cues.length}  frames: ${frames.length}`);
console.log(`time: ${((Date.now()-t0)/1000).toFixed(1)}s`);
console.log(`heap delta: ${((after-before)/1e6).toFixed(1)} MB`);
console.log(`total SVG text: ${(svgBytes/1e6).toFixed(1)} MB`);
console.log(`avg SVG size: ${Math.round(svgBytes/frames.length/1024)} KB`);
